apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: userlogin
spec:
  selector:
    app: userlogin
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 3000