apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: userlogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userlogin
  template:
    metadata:
      labels:
        app: userlogin
    spec:
      containers:
        - name: userlogin
          image: userlogin/user1.0
          ports:
            - containerPort: 8080